### DISCUSSION TITLE
[Item] note links

### DISCUSSION THREAD

**Discussion by windingwind** [windingwind/zotero-better-notes#243] [Note Templates]
Insert the selected notes' links.
Author: @windingwind

```yaml
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[item] note link"
content: |-
  // @author windingwind
  // @link https://github.com/windingwind/zotero-better-notes/discussions/243
  // @use-markdown
  [${topItem.getNoteTitle()}](${Zotero.BetterNotes.api.convert.note2link(topItem)})

```

**Comment by macrospecter** [comment]
This sounded like a really helpful template, but it's now outdated (since it refers to Knowledge4Zotero). Would it be possible to get an update? I tried fiddling with it but can't get it to work. Thank you!

**Reply by windingwind** [reply]
Updated for the latest beta version (v1.1.4-4).

**Comment by macrospecter** [comment]
Is it possible to create a version of this template that automatically selects the open note or its parent item as the source of the link, rather than requiring selection of the item in a popup? I've been using a variation of this template for some time to put a link to the open note at the start of every note (so that I can open it again from within my markdown editor after it exports), but it takes awhile to sort through the relevant articles and find the one that's open.

**Reply by windingwind** [reply]
Only menu-File-Create note from template or export template to file supports using the selected items in the library as input.

If you mean to create a note link of the target note itself, using the `[text]` template would be enough.

**Reply by macrospecter** [reply]
Thanks for the reply! My File menu doesn't have the Create Note from Template option, but I was able to do as you suggest by using the + button > New Item Note from Template option within the Zotero PDF reader. So that's a solution for new notes. 

But I have one question about how to adapt the text template for adding links to **existing** notes. I've been using a template (a variant of one of yours) that inserts the item link as a hyperlink over the item's author, title, and year. I'm pasting the template immediately below. Could you perhaps point me in the right direction for modifying this template to use the text template for the link to the target note (I guess:  <a href="${link}">${linkText}</a>), rather than the function that grabs a link to the specified library item? I tried editing it myself but I must be missing something.

${await new Promise(async (resolve) => {
  async function getPDFLink(item) {
    const att = await item.getBestAttachment();
    if (!att || !att.isPDFAttachment()) {
      return "";
    }
    key = att.key;
    if (att.libraryID === 1) {
      return `zotero://open-pdf/library/items/${key}`;
    } else {
      groupID = Zotero.Libraries.get(att.libraryID).id;
      return `zotero://open-pdf/groups/${groupID}/items/${key}`;
    }
  }
  const creators = topItem.getCreators();
  let content = "";
const title = topItem.getField("title");
  const year = topItem.getField("year");
  if (creators.length === 0) {
    content = "no author";
  } else if (creators.length === 1) {
    content = `${creators[0].lastName}, ${title}, ${year}`;
  } else {
    content = `${creators[0].lastName} et al., ${title}, ${year}`;
  }
  // The getPDFLink is from above
  const link = await getPDFLink(topItem);
  let str = `<a href="${link}">${content}</a>`;
  resolve(str);
})}

**Reply by windingwind** [reply]
1. You can find the available variables of the text template here: https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#text
2. There is a `targetNoteItem`. You can call `Zotero.BetterNotes.api.convert.note2link(targetNoteItem)` to get the link of that note item. Wrap the code inside `${}`, following the construction here: https://github.com/windingwind/zotero-better-notes/blob/master/docs/about-note-template.md#script-in-note-template
3. Write the template in MarkDown with `// @use-markdown`:

```yaml
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[text] current note link"
content: |-
  // @author windingwind
  // @link https://github.com/windingwind/zotero-better-notes/discussions/243
  // @use-markdown
  [Current Zotero Note](${Zotero.BetterNotes.api.convert.note2link(targetNoteItem)})
```
