### DISCUSSION TITLE
[QuickInsert](insert note content instead of link)

### DISCUSSION THREAD

**Discussion by windingwind** [windingwind/zotero-better-notes#245] [Note Templates]
Insert the note content, instead of a note link. See #174 

```yaml
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[QuickInsertV2]"
content: |-
  ${{
  	return await Zotero.BetterNotes.api.convert.note2html(subNoteItem, {targetNoteItem: noteItem, dryRun: _env.dryRun});
  }}$
```
