### DISCUSSION TITLE
[Item]Read Articles with All MetaData 包含所有元数据的论文阅读模板

### DISCUSSION THREAD

**Discussion by Kingw413** [windingwind/zotero-better-notes#598] [Note Templates]
Type: Item

Description: This template is to conclude article with metadata 包含文章元数据以及pdf附件的论文阅读模板

Screenshots: ![屏幕截图 2023-08-02 170456](https://github.com/windingwind/zotero-better-notes/assets/68884677/a8f2906b-db53-4b84-9284-325daf89565a)

To import this template:
1. Copy the template below. 复制相应版本的模板代码
<details style="text-indent: 2em">

<summary>Zotero 6版本</summary>

```html
name: "[Item] conclude article with metadata 论文阅读并包含元数据"
content: |-
  // @author Kingw413
  // @link [PUBLISH PAGE URL](https://github.com/windingwind/zotero-better-notes/discussions/598)
    <h1 style="text-align: center">${topItem.getField('title')}</h1>
    <hr/>
    <h2 style="color: #1B5E20; background-color:#F1F8E9;">💡 Meta Data</h2>
    
    <table>
        <tr>
            <th style="background-color:#dbeedd;">
                <p style="text-align: left;">Title </p>
            </th>
            <td style="background-color:#dbeedd;">
                ${topItem.getField('title')}
            </td>
        </tr>
        <tr>
            <th style="background-color:#f3faf4;">
                <p style="text-align: left">Journal </p>
            </th>
            <td style="background-color:#f3faf4;">
                ${topItem.getField('publicationTitle')}
            </td>
        </tr>
        <tr>
            <th style="background-color:#dbeedd;">
                <p style="text-align: left">Authors </p>
            </th>
            <td style="background-color:#dbeedd;">
                ${topItem.getCreators().map((v)=>v.firstName+" "+v.lastName).join("; ")}
            </td>
        </tr>
        <tr>
            <th style="background-color:#f3faf4;">
                <p style="text-align: left">Pub. date </p>
            </th>
            <td style="background-color:#f3faf4;">
                ${topItem.getField('date')}
            </td>
        </tr>
        <tr>
            <th style="background-color:#dbeedd;"
                <!-- 期刊标签 -->
                <p style="text-align: left">期刊标签</p>
            </th>
            <td style="background-color:#dbeedd;">
               ${(() => {let space = " ㅤㅤ ㅤㅤ"
                return Array.prototype.map.call(Zotero.ZoteroStyle.data.ztoolkit.ItemTree.globalCache.renderCellHooks.PublicationTags(
      0,
      Zotero.ZoteroStyle.data.ztoolkit.ItemTree.fieldHooks.globalCache.getFieldHooks.PublicationTags(
      "", true, true,
      topItem, undefined)
      ).childNodes,
      e => {
      e.innerText = space + space + e.innerText + space + space;
      return e.outerHTML
      }).join(space)
      })()
      }
            </td>
        </tr>
        <tr>
            <th style="background-color:#f3faf4;">
                <p style="text-align: left">DOI </p>
            </th>
            <td style="background-color:#f3faf4;">
                <a href="https://doi.org/${topItem.getField('DOI')}">${topItem.getField('DOI')}</a>
            </td>
        </tr>
        <tr>
            <th style="background-color:#dbeedd;">
                <p style="text-align: left">附件</p>
            </th>
            <td style="background-color:#dbeedd;">
                <a href=zotero://open-pdf/0_${Zotero.Items.get(topItem.getAttachments()).filter((i) => i.isPDFAttachment())[0].key}>
                  ${Zotero.Items.get(topItem.getAttachments()).filter((i)=> i.isPDFAttachment())[0].getFilename()} 
    </a>
            </td>
        </tr>
    
    </table>
    
    
    </table>
    </span></h1>\n <h2 style="color:  #E65100; background-color:  #FFF8E1;">📜 研究背景 & 基础 & 目的</h2>
    <hr/>
    <p></p>
    </span></h1>\n <h2 style="color:#2E7D32; background-color:    #F1F8E9;">&#x1F4CA 研究内容</h2>
    <hr/>
    <p></p>
    </span></h1>\n <h2 style="color:#4A148C; background-color:    #F5F5F5;">🚩 研究结论</h2>
    <hr/>
    <p></p>
    
    </span></h1>\n <h2 style="color: #006064; background-color:   #E0F7FA;">📌 感想 & 疑问</h2>
    <hr/>
    <p></p>
    </span></h1>\n <h2 style="color:#1565C0; background-color:   #E1F5FE;">🔬 理论推导</h2>
    <hr/>
    <p></p>
```
</details>

<details style="text-indent: 2em">

<summary>Zotero 7版本</summary>

```html
name: "[Item] conclude article with metadata 论文阅读并包含元数据"
content: |-
  // @author Kingw413
  // @link [PUBLISH PAGE URL](https://github.com/windingwind/zotero-better-notes/discussions/598)
  <h1 style="text-align: center">${topItem.getField('title')}</h1>
  <hr/>
  <h2 style="color: #1B5E20; background-color:#F1F8E9;">💡 Meta Data</h2>
  
  <table>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left;">Title</p>
          </th>
          <td style="background-color:#dbeedd;">
              ${topItem.getField('title')}
          </td>
      </tr>
      <tr>
          <th style="background-color:#f3faf4;">
              <p style="text-align: left">Journal</p>
          </th>
          <td style="background-color:#f3faf4;">
              ${topItem.getField('publicationTitle')}
          </td>
      </tr>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left">Authors</p>
          </th>
          <td style="background-color:#dbeedd;">
              ${topItem.getCreators().map((v)=>v.firstName+" "+v.lastName).join("; ")}
          </td>
      </tr>
      <tr>
          <th style="background-color:#f3faf4;">
              <p style="text-align: left">Pub. date</p>
          </th>
          <td style="background-color:#f3faf4;">
              ${topItem.getField('date')}
          </td>
      </tr>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left">期刊标签</p>
          </th>
          <td style="background-color:#dbeedd;">
              ${(() => {
                let tags = Zotero.ZoteroStyle.data.ztoolkit.ItemTree.fieldHooks.globalCache.getFieldHooks.PublicationTags(
                  "", true, true, topItem, undefined);
                let out = "";
  			if (!tags){
                const jsonStartIndex = tags.indexOf('{');
                if (jsonStartIndex !== -1) {
                  tags = tags.slice(jsonStartIndex);
                }
  
                const keyValuePairs = JSON.parse(tags);
                const colors = ["#ff6666", "#ffd400", "#5fb236", "#2ea8e5", "#a28ae5"];
  
  
                for (const key in keyValuePairs) {
                  if (key === "sci") {
                    out += `<span style="background-color: ${colors[0]}; margin-right: 20px; padding:5px">SCI ${keyValuePairs[key]}</span>`;
                  }
                  if (key === "sciUp") {
                    out += `<span style="background-color: ${colors[1]}; margin-right: 20px; padding:5px">中科院 ${keyValuePairs[key]}</span>`;
                  }
                  if (key === "sciif") {
                    out += `<span style="background-color: ${colors[2]}; margin-right: 20px; padding:5px">IF ${keyValuePairs[key]}</span>`;
                  }
                  if (key === "pku") {
                    out += `<span style="background-color: ${colors[3]}; margin-right: 20px; padding:5px"> 北核</span>`;
                  }
                  if (key === "cssci") {
                    out += `<span style="background-color: ${colors[4]}; margin-right: 20px; padding:5px"> ${keyValuePairs[key]}</span>`;
                  }
                }
  			}
            return out;
              })()}
          </td>
      </tr>
      <tr>
          <th style="background-color:#f3faf4;">
              <p style="text-align: left">DOI</p>
          </th>
          <td style="background-color:#f3faf4;">
              <a href="https://doi.org/${topItem.getField('DOI')}">${topItem.getField('DOI')}</a>
          </td>
      </tr>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left">附件</p>
          </th>
          <td style="background-color:#dbeedd;">
              <a href="zotero://open-pdf/0_${Zotero.Items.get(topItem.getAttachments())[0].key}">
                  ${Zotero.Items.get(topItem.getAttachments())[0].getFilename()}
              </a>
          </td>
      </tr>
  </table>
  
  <h2 style="color:  #E65100; background-color:  #FFF8E1;">📜 研究背景 & 基础 & 目的</h2>
  <hr/>
  <p></p>
  
  <h2 style="color:#2E7D32; background-color:    #F1F8E9;">&#x1F4CA 研究内容</h2>
  <hr/>
  <p></p>
  
  <h2 style="color:#4A148C; background-color:    #F5F5F5;">🚩 研究结论</h2>
  <hr/>
  <p></p>
  
  <h2 style="color: #006064; background-color:   #E0F7FA;">📌 感想 & 疑问</h2>
  <hr/>
  <p></p>
  
  <h2 style="color:#1565C0; background-color:   #E1F5FE;">🔬 理论推导</h2>
  <hr/>
  <p></p>
```
</details>

2. Goto Zotero menubar, click `Edit`->`New Template from Clipboard`. 进入Zotero，`编辑` -> `从剪贴板导入新模板`
3. Click OK.

**Comment by Kingw413** [comment]
说明：
- 本模板基于[SCI论文阅读模板](https://github.com/windingwind/zotero-better-notes/discussions/339#discussion-4812946)，修改了原模版的bug
- 在MetaData增添了指向pdf附件的链接，可以在阅读笔记时快速打开论文pdf（前提是给条目增添了相应的pdf附件）
- 在MetaData中增添了期刊标签选项，可以显示分区（前提是安装了zotero-style插件）,参考自[标签模板示例](https://github.com/windingwind/zotero-better-notes/discussions/521#discussion-5298711)
- 请根据自己使用的Zotero版本选择相应的模板代码。（Zotero7版本对应的代码也适配于Zotero6，不过建议使用各自对应的版本代码）
- 感谢模板使用过程中大家提出的问题，以及提供的一些解决方案🤩。[thebetter2](https://github.com/windingwind/zotero-better-notes/discussions/598#discussioncomment-6924817), [cohesioncompany](https://github.com/cohesioncompany), [opacscdbph44](https://github.com/windingwind/zotero-better-notes/discussions/598#discussioncomment-6922652), [junjunzi0830](https://github.com/windingwind/zotero-better-notes/discussions/598#discussioncomment-6736640), [Zhangxigu](https://github.com/windingwind/zotero-better-notes/discussions/598#discussioncomment-6780637)等

**Reply by Kieran0526** [reply]
您好可以提供一下模板代码吗

**Reply by thebetter2** [reply]
我用chatgpt修改过大佬上面的zotero7的代码，正确的代码如下
修改了如果期刊标签为空则会报错 “ unexpected end of data at line 1 column 1 of the JSON data ”的错误，实现效果是：如果期刊标签为空则输出空。
``` css
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[Item] conclude article with metadata 论文阅读并包含元数据"
content: |-
  // @author Kingw413
  // @link [PUBLISH PAGE URL](https://github.com/windingwind/zotero-better-notes/discussions/598)
  <h1 style="text-align: center">${topItem.getField('title')}</h1>
  <hr/>
  <h2 style="color: #1B5E20; background-color:#F1F8E9;">💡 Meta Data</h2>
  
  <table>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left;">Title</p>
          </th>
          <td style="background-color:#dbeedd;">
              ${topItem.getField('title')}
          </td>
      </tr>
      <tr>
          <th style="background-color:#f3faf4;">
              <p style="text-align: left">Journal</p>
          </th>
          <td style="background-color:#f3faf4;">
              ${topItem.getField('publicationTitle')}
          </td>
      </tr>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left">Authors</p>
          </th>
          <td style="background-color:#dbeedd;">
              ${topItem.getCreators().map((v)=>v.firstName+" "+v.lastName).join("; ")}
          </td>
      </tr>
      <tr>
          <th style="background-color:#f3faf4;">
              <p style="text-align: left">Pub. date</p>
          </th>
          <td style="background-color:#f3faf4;">
              ${topItem.getField('date')}
          </td>
      </tr>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left">期刊标签</p>
          </th>
          <td style="background-color:#dbeedd;">
              ${(() => {
                let tags = Zotero.ZoteroStyle.data.ztoolkit.ItemTree.fieldHooks.globalCache.getFieldHooks.PublicationTags(
                  "", true, true, topItem, undefined);
                let out = "";
  			if (!tags){
  				  out += `<span></span>`;
  			}else{
                const jsonStartIndex = tags.indexOf('{');
                if (jsonStartIndex !== -1) {
                  tags = tags.slice(jsonStartIndex);
                }
                let regex = /"(sci|sciif)":"([^"]+)"/g;
                let matches = tags.match(regex);
  
                const keyValuePairs = JSON.parse(tags);
                const colors = ["#ff6666", "#ffd400", "#5fb236", "#2ea8e5", "#a28ae5"];
  
  
                for (const key in keyValuePairs) {
                  if (key === "sci") {
                    out += `<span style="background-color: ${colors[0]}; margin-right: 20px; padding:5px">SCI ${keyValuePairs[key]}</span>`;
                  }
                  if (key === "sciUp") {
                    out += `<span style="background-color: ${colors[1]}; margin-right: 20px; padding:5px">中科院 ${keyValuePairs[key]}</span>`;
                  }
                  if (key === "sciif") {
                    out += `<span style="background-color: ${colors[2]}; margin-right: 20px; padding:5px">IF ${keyValuePairs[key]}</span>`;
                  }
                  if (key === "pku") {
                    out += `<span style="background-color: ${colors[3]}; margin-right: 20px; padding:5px"> 北核</span>`;
                  }
                  if (key === "cssci") {
                    out += `<span style="background-color: ${colors[4]}; margin-right: 20px; padding:5px"> ${keyValuePairs[key]}</span>`;
                  }
                }
  			}
                return out;
              })()}
          </td>
      </tr>
      <tr>
          <th style="background-color:#f3faf4;">
              <p style="text-align: left">DOI</p>
          </th>
          <td style="background-color:#f3faf4;">
              <a href="https://doi.org/${topItem.getField('DOI')}">${topItem.getField('DOI')}</a>
          </td>
      </tr>
      <tr>
          <th style="background-color:#dbeedd;">
              <p style="text-align: left">附件</p>
          </th>
          <td style="background-color:#dbeedd;">
              <a href="zotero://open-pdf/0_${Zotero.Items.get(topItem.getAttachments())[0].key}">
                  ${Zotero.Items.get(topItem.getAttachments())[0].getFilename()}
              </a>
          </td>
      </tr>
  </table>
  
  <h2 style="color:  #E65100; background-color:  #FFF8E1;">📜 研究背景 & 基础 & 目的</h2>
  <hr/>
  <p></p>
  
  <h2 style="color:#2E7D32; background-color:    #F1F8E9;">&#x1F4CA 研究内容</h2>
  <hr/>
  <p></p>
  
  <h2 style="color:#4A148C; background-color:    #F5F5F5;">🚩 研究结论</h2>
  <hr/>
  <p></p>
  
  <h2 style="color: #006064; background-color:   #E0F7FA;">📌 感想 & 疑问</h2>
  <hr/>
  <p></p>
  
  <h2 style="color:#1565C0; background-color:   #E1F5FE;">🔬 理论推导</h2>
  <hr/>
  <p></p>

```
