### DISCUSSION TITLE
[ExportMDFileContent] Export/Sync with Obsidian `[[link]]`

### DISCUSSION THREAD

**Discussion by windingwind** [windingwind/zotero-better-notes#646] [Note Templates]
See #645 

```yaml
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[ExportMDFileContent]"
content: |-
  ${mdContent.replaceAll("\\[\\[", "[[")}
```

Requires BN 1.1.4-16 or higher.
