### DISCUSSION TITLE
[QuickInsertV2]插入正链笔记时，只显示跳转用的链接，将其他内容插入为纯文本

### DISCUSSION THREAD

**Discussion by fangzhanlin** [windingwind/zotero-better-notes#649] [Note Templates]
将[QuickInsertV2]替换为该模板，向工作区插入笔记时，跳转链接将简化，其余文本会全部保留。适配版本zotero6.0.26，其余未作测试。

笔记效果如图所示：
<img width="743" alt="Snipaste_2023-08-24_12-35-05" src="https://github.com/windingwind/zotero-better-notes/assets/64974830/b3aba97d-83df-4989-9374-dcb6478b902d">

代码：
```
<p><a href="${link}" rel="noopener noreferrer nofollow">${subNoteItem.getField("conferenceName") ? subNoteItem.getField("conferenceName") : link}</a>${subNoteItem.getNote()}</p>
```

**Comment by windingwind** [comment]
Use this template to embed the images in the linked note.

<img width="1512" alt="image" src="https://github.com/windingwind/zotero-better-notes/assets/33902321/83336a52-0771-4fda-a9ca-1bb630cdb425">


```yaml
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[QuickInsertV2]"
content: |-
  // @author sydlfl, windingwind
  // @link https://github.com/windingwind/zotero-better-notes/discussions/649
  // @min-version 1.1.4-19
  // @use-markdown
  [${subNoteItem.getField("conferenceName") ? subNoteItem.getField("conferenceName") : link}](${link})
  
  ${await Zotero.BetterNotes.api.convert.note2html(subNoteItem, {targetNoteItem: _env.dryRun ? undefined : noteItem})}
```
