### DISCUSSION TITLE
[ExportMDFileContent] Use `-` in exported markdown's bullet list

### DISCUSSION THREAD

**Discussion by windingwind** [windingwind/zotero-better-notes#768] [Note Templates]
### Description

See https://github.com/windingwind/zotero-better-notes/issues/767

### Screenshots

See https://github.com/windingwind/zotero-better-notes/issues/767

### Test on Zotero version

7.0.0-beta.47+f012a348a

### Test on Better Notes version

1.1.4-26

### Template Type

ExportMDFileContent

### Template Share Code

```yaml
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[ExportMDFileContent]"
content: |-
  ${{
  	return mdContent.replace(/^(\s*)\*/gm, "$1-");
  }}$
```
