### DISCUSSION TITLE
[Text] Markdown from clipboard

### DISCUSSION THREAD

**Discussion by windingwind** [windingwind/zotero-better-notes#824] [Note Templates]
### Description

Insert markdown from clipboard

### Screenshots

-

### Test on Zotero version

7.0.0-beta.52+2f8e536f2

### Test on Better Notes version

1.4.4-44

### Template Type

Text

### Template Share Code

```yaml
# This template is specifically for importing/sharing, using better 
# notes 'import from clipboard': copy the content and
# goto Zotero menu bar, click Edit->New Template from Clipboard.  
# Do not copy-paste this to better notes template editor directly.
name: "[text] Markdown from clipboard"
content: |-
  ${{
  	const str = Zotero.Utilities.Internal.getClipboard("text/plain");
  	return Zotero.BetterNotes.api.convert.md2html(str);
  }}$
```
