### ISSUE TITLE
[Feature] Don't reset the YAML metadata when syncing

### ISSUE THREAD

**Issue by davidoskky** [windingwind/zotero-better-notes#527]
I export notes and keep them in sync, I do edit them externally as well. I'd like to be able to add things to the yaml frontmatter, but when the note gets synced with Zotero the yaml gets resetted to the exported one.
It would be nice if the sync process kept metadata contained in the yaml untouched.
Maybe you could introduce a sort of divider after which you can add your own metadata to the yaml and that is preserved.

**Comment by windingwind** [comment]
We cannot save yaml data in a Zotero note, keeping them seem to be not possible.

**Comment by windingwind** [comment]
That could be a workaround.

**Comment by windingwind** [comment]
But, the note item does not have metadata. No insurance that the note item has a parent item with writable metadata.

**Comment by Xieading** [comment]
我遇到了同样的问题，每次同步的时候会自动刷新YAML，这让我无法在obsidian中使用文档属性的功能，很苦恼。
I had the same problem that YAML was automatically refreshed every time I synchronized, which made it difficult for me to use the document properties functionality in obsidian, which was very distressing.

**Comment by windingwind** [comment]
OK, so a possible workaround is to *keep* the YAML key-value starting with `$` during syncing (but they will not affect Zotero data). Would that be acceptable?

Example:

In synced markdown:
```yaml
- libraryID: 123 # generated by BN, unmutable
- $keptData: xyz # added by user but starts with `$`, not overridden during syncing
- otherData: ABC # added by user, overridden during syncing
```

After syncing:
```yaml
- libraryID: AJHKHS # generated by BN, unmutable
- $keptData: xyz # added by user but starts with `$`, not overridden during syncing
```
